# Generated by Django 3.1.4 on 2021-01-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0002_q_and_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_and_a',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QA', to='Quizzer.quiz'),
        ),
    ]
