# Generated by Django 3.1.4 on 2021-02-01 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quizzer', '0005_userquizcreator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q_and_a',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
