# Generated by Django 3.1.4 on 2021-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0006_auto_20210201_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='availableTo',
            field=models.CharField(choices=[('a', 'Public'), ('b', 'Private'), ('c', 'Friends')], default='a', max_length=1),
        ),
    ]
