# Generated by Django 3.1.4 on 2021-02-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0007_quiz_availableto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='availableTo',
            new_name='visibleTo',
        ),
    ]
