# Generated by Django 3.1.4 on 2021-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0008_auto_20210202_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='modifiedBy',
            field=models.CharField(choices=[('a', 'Public'), ('b', 'Private'), ('c', 'Friends')], default='a', max_length=1, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='visibleTo',
            field=models.CharField(choices=[('a', 'Public'), ('b', 'Private'), ('c', 'Friends')], default='a', max_length=1, verbose_name='Visible To'),
        ),
    ]
