# Generated by Django 3.1.4 on 2021-02-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0010_auto_20210202_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
