# Generated by Django 3.1.4 on 2021-02-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_friend_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
